osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - clang-3.7
      - graphicsmagick

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-linux-amd64-1.2.0.tar.gz | tar -xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git-lfs-1.2.0/git-lfs pull; fi

install:
- nvm install 6
- npm install npm -g
#- npm install electron-builder@next # force install next version to test electron-builder
- npm install
- npm prune
- cd app
- npm install
- npm prune
- cd ..

script: cd app && npm run make-dist && cd .. && npm run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
