version: 0.4.0

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune
  - cd app
  - npm install
  - npm prune
  - cd ..

build_script:
  - node --version
  - npm --version
  - cd app
  - npm run make-dist
  - cd ..
  - npm run dist

test: off
